// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqiueydxpgxcqelzuosu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaXVleWR4cGd4Y3FlbHp1b3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDQzODAsImV4cCI6MjA2NjYyMDM4MH0.MpwYZOBekSyyOSFC3QvJtmvebPxImqSAl98jUejGRso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);